services: 

  nginx: 
    build: requirements/nginx/. 
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports: 
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./key.pem:/etc/nginx/ssl/key.pem
    networks: 
      inception:
    restart: always
    env_file:
      - ./.env

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
    restart: always
    env_file:
      - ./.env

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      inception:
    restart: always
    env_file:
      - ./.env
    expose:
      - "3306"

networks:
  inception: 
    driver: bridge  # Use the bridge network driver to allow containers to communicate with each other on a private network.

volumes:
  wordpress:
    driver: local 
    driver_opts:
      type: none  
      o: bind      
      device: /home/lpicoli-/data/html  
  database:
    driver: local  # Use the default local driver to manage the volume for the database.
    driver_opts:
      type: none   # Use an existing directory on the host as a bind mount.
      o: bind      # Bind the host directory to the container for data sharing.
      device: /home/lpicoli-/data/mysql  # The host directory where the MySQL data will be stored.


