FROM debian:12.7-slim
RUN apt update && apt upgrade -y && apt install -y \
    php-fpm \
    php-mysqli \
    curl 

COPY www.conf /etc/php/8.2/fpm/pool.d/.
COPY script.sh .
RUN chmod 777 script.sh

CMD ["./script.sh"]

